// <auto-generated />
namespace KendoDreamCarShopper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Config : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Config));
        
        string IMigrationMetadata.Id
        {
            get { return "201301161515045_Config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
