// <auto-generated />
namespace KendoDreamCarShopper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddYearToModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddYearToModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201301061351063_AddYearToModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
