// <auto-generated />
namespace KendoDreamCarShopper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReelInScope : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReelInScope));
        
        string IMigrationMetadata.Id
        {
            get { return "201302202145181_ReelInScope"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
